# Generated by Django 3.0.4 on 2020-03-30 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('kitchen', '0003_store'),
  ]

  operations = [
      migrations.CreateModel(
          name='Item',
          fields=[
              ('id',
               models.AutoField(auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID')),
              ('name', models.CharField(max_length=255)),
              ('bestbefore', models.DateField()),
              ('price', models.DecimalField(decimal_places=2, max_digits=10)),
              ('quantity',
               models.IntegerField(
                   default=0,
                   validators=[django.core.validators.MinValueValidator(0)])),
              ('preferred_stores', models.ManyToManyField(to='kitchen.Store')),
              ('shelf',
               models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                 to='kitchen.Shelf')),
              ('user',
               models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                 to=settings.AUTH_USER_MODEL)),
          ],
      ),
  ]
